package org.pushio.datacenter.entity;

// Generated 2015-10-13 18:23:33 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeePosts generated by hbm2java
 */
@Entity
@Table(name = "employee_posts")
public class EmployeePosts extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7148269709181566142L;

	private Employee employee;
	private Post post;

	public EmployeePosts() {
	}

	public EmployeePosts(Employee employee, Post post) {
		this.employee = employee;
		this.post = post;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POST_ID", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

}
