package org.pushio.datacenter.entity;

// Generated 2015-10-13 18:23:33 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PostFunction generated by hbm2java
 */
@Entity
@Table(name = "post_function")
public class PostFunction  extends BaseEntity implements java.io.Serializable {


	private Function function;
	private Post post;
	private Integer isMenu;

	public PostFunction() {
	}

	public PostFunction(Function function, Post post) {
		this.function = function;
		this.post = post;
	}

	public PostFunction(Function function, Post post, Integer isMenu) {
		this.function = function;
		this.post = post;
		this.isMenu = isMenu;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCUNTION_ID", nullable = false)
	public Function getFunction() {
		return this.function;
	}

	public void setFunction(Function function) {
		this.function = function;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POST_ID", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "IS_MENU")
	public Integer getIsMenu() {
		return this.isMenu;
	}

	public void setIsMenu(Integer isMenu) {
		this.isMenu = isMenu;
	}

}
