package org.pushio.datacenter.entity;

// Generated 2015-11-4 10:25:20 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post")
public class Post  extends BaseEntity implements java.io.Serializable {



	private String name;
	private String indexPage;
	private Integer needFilter;
	private Set<EmployeePosts> employeePostses = new HashSet<EmployeePosts>(0);
	private Set<PostFunction> postFunctions = new HashSet<PostFunction>(0);

	public Post() {
	}

	public Post(Long addUserId, Date addDate,
			Date modifyDate, Long modifyUserId, String name, String indexPage,
			Integer needFilter, Set<EmployeePosts> employeePostses,
			Set<PostFunction> postFunctions) {
		this.addDate = addDate;
		this.modifyDate = modifyDate;
		this.name = name;
		this.indexPage = indexPage;
		this.needFilter = needFilter;
		this.employeePostses = employeePostses;
		this.postFunctions = postFunctions;
	}





	/*@Column(name = "ADD_USER_ID")
	public Long getAddUserId() {
		return this.addUserId;
	}

	public void setAddUserId(Long addUserId) {
		this.addUserId = addUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ADD_DATE", length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_DATE", length = 10)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MODIFY_USER_ID")
	public Long getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Long modifyUserId) {
		this.modifyUserId = modifyUserId;
	}*/

	@Column(name = "NAME", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "INDEX_PAGE", length = 64)
	public String getIndexPage() {
		return this.indexPage;
	}

	public void setIndexPage(String indexPage) {
		this.indexPage = indexPage;
	}

	@Column(name = "NEED_FILTER")
	public Integer getNeedFilter() {
		return this.needFilter;
	}

	public void setNeedFilter(Integer needFilter) {
		this.needFilter = needFilter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<EmployeePosts> getEmployeePostses() {
		return this.employeePostses;
	}

	public void setEmployeePostses(Set<EmployeePosts> employeePostses) {
		this.employeePostses = employeePostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<PostFunction> getPostFunctions() {
		return this.postFunctions;
	}

	public void setPostFunctions(Set<PostFunction> postFunctions) {
		this.postFunctions = postFunctions;
	}

}
